# Generated by Django 5.0.7 on 2025-12-14 00:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0001_initial'),
        ('reservas', '0002_remove_reserva_reserva_fecha_futura_and_more'),
        ('residentes', '0006_merge_20250929_0502'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='reserva_fecha_futura',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('fecha_reserva__gte', datetime.date(2025, 12, 14))), name='reserva_fecha_futura'),
        ),
    ]
