# Generated by Django 5.0.7 on 2025-12-16 19:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_comunes', '0001_initial'),
        ('personal', '0002_personal_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título breve de la tarea', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del mantenimiento requerido')),
                ('tipo', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo'), ('emergencia', 'Emergencia'), ('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('limpieza', 'Limpieza Especial')], help_text='Tipo de mantenimiento', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad de la tarea', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la tarea', max_length=15)),
                ('fecha_asignacion', models.DateTimeField(blank=True, help_text='Fecha en que se asignó al personal', null=True)),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ubicación específica (ej: "Ascensor 2", "Piscina - Bomba de agua")', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la tarea')),
                ('fecha_limite', models.DateField(help_text='Fecha límite para completar la tarea')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha en que se inició el trabajo', null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha en que se completó la tarea', null=True)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto estimado en Bs.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_real', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo real ejecutado en Bs.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales o notas del trabajo realizado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('area_comun', models.ForeignKey(blank=True, help_text='Área común donde se realizará el mantenimiento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_mantenimiento', to='areas_comunes.areacomun')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('personal_asignado', models.ForeignKey(blank=True, help_text='Personal responsable de ejecutar la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('asignacion', 'Asignación'), ('inicio', 'Inicio de trabajo'), ('actualizacion', 'Actualización'), ('completado', 'Completado'), ('cancelacion', 'Cancelación'), ('comentario', 'Comentario')], help_text='Tipo de acción realizada', max_length=15)),
                ('descripcion', models.TextField(help_text='Descripción de la acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('estado_anterior', models.CharField(blank=True, help_text='Estado antes del cambio', max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, help_text='Estado después del cambio', max_length=15)),
                ('realizado_por', models.ForeignKey(help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del material o insumo', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del material')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad utilizada', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad', models.CharField(help_text='Unidad de medida (ej: kg, m, litros, unidades)', max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo por unidad en Bs.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor del material', max_length=200)),
                ('fecha_uso', models.DateField(default=django.utils.timezone.now, help_text='Fecha de uso del material')),
                ('tarea', models.ForeignKey(help_text='Tarea asociada', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'verbose_name': 'Material/Insumo',
                'verbose_name_plural': 'Materiales/Insumos',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.AddIndex(
            model_name='tareamantenimiento',
            index=models.Index(fields=['estado', 'prioridad'], name='mantenimien_estado_089576_idx'),
        ),
        migrations.AddIndex(
            model_name='tareamantenimiento',
            index=models.Index(fields=['fecha_limite'], name='mantenimien_fecha_l_d44716_idx'),
        ),
        migrations.AddIndex(
            model_name='tareamantenimiento',
            index=models.Index(fields=['personal_asignado', 'estado'], name='mantenimien_persona_21ebca_idx'),
        ),
    ]
