# Generated by Django 5.0.7 on 2025-12-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('residentes', '0007_residente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='categoria_incidencia',
            field=models.CharField(blank=True, choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('cerrajeria', 'Cerrajería'), ('pintura', 'Pintura'), ('jardineria', 'Jardinería'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('ascensor', 'Ascensor'), ('piscina', 'Piscina'), ('gimnasio', 'Gimnasio'), ('estacionamiento', 'Estacionamiento'), ('areas_comunes', 'Áreas Comunes'), ('otro', 'Otro')], help_text='Categoría de la incidencia reportada por residente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='es_incidencia',
            field=models.BooleanField(default=False, help_text='Indica si fue reportada por un residente desde la app móvil'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='imagen_incidencia',
            field=models.ImageField(blank=True, help_text='Foto del problema reportado', null=True, upload_to='incidencias/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tareamantenimiento',
            name='reportado_por_residente',
            field=models.ForeignKey(blank=True, help_text='Residente que reportó la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to='residentes.residente'),
        ),
    ]
