# Generated by Django 5.0.7 on 2025-12-08 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0006_merge_20250929_0502'),
        ('unidades', '0002_add_codigo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ruido', 'Ruido excesivo'), ('estacionamiento', 'Estacionamiento indebido'), ('area_comun', 'Mal uso de área común'), ('pago_atrasado', 'Pago de expensa atrasado'), ('dano_propiedad', 'Daño a propiedad común'), ('incumplimiento', 'Incumplimiento de reglamento'), ('otro', 'Otro')], help_text='Tipo de infracción', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la infracción')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la multa (mínimo Bs. 50)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('50.00'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('en_disputa', 'En disputa')], default='pendiente', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True, help_text='Fecha de emisión de la multa')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite de pago')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que se pagó la multa', null=True)),
                ('recargo_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo adicional por mora', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones adicionales')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó la multa', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('residente', models.ForeignKey(help_text='Residente responsable', on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='residentes.residente')),
                ('unidad', models.ForeignKey(help_text='Unidad habitacional asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='unidades.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
                'ordering': ['-fecha_emision', '-id'],
                'indexes': [models.Index(fields=['estado', 'fecha_vencimiento'], name='multas_estado_764c2f_idx'), models.Index(fields=['residente', 'estado'], name='multas_residen_0adf98_idx'), models.Index(fields=['tipo'], name='multas_tipo_495a20_idx')],
            },
        ),
    ]
