# Generated by Django 5.0.7 on 2025-12-17 01:15

import residentes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0006_merge_20250929_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del residente para reconocimiento facial (formato JPG/PNG)', null=True, upload_to=residentes.models.residente_foto_path, verbose_name='Foto de Perfil'),
        ),
    ]
