# Generated by Django 5.0.7 on 2025-12-08 16:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0006_merge_20250929_0502'),
        ('unidades', '0002_add_codigo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Placa del vehículo (ej: ABC-1234)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido. Use: ABC-1234 o ABC1234', regex='^[A-Z]{3}-?\\d{4}$')])),
                ('tipo', models.CharField(choices=[('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('camioneta', 'Camioneta'), ('suv', 'SUV'), ('otro', 'Otro')], default='auto', max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('año', models.PositiveSmallIntegerField(blank=True, help_text='Año del vehículo', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateField(auto_now_add=True, help_text='Fecha en que se autorizó el vehículo')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento de autorización (opcional)', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('foto_vehiculo', models.ImageField(blank=True, help_text='Foto del vehículo o placa', null=True, upload_to='vehiculos/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('residente', models.ForeignKey(help_text='Residente propietario del vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='residentes.residente')),
                ('unidad', models.ForeignKey(help_text='Unidad habitacional asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='unidades.unidadhabitacional')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['placa'], name='vehiculos_placa_0848cc_idx'), models.Index(fields=['estado'], name='vehiculos_estado_bf04b7_idx'), models.Index(fields=['residente'], name='vehiculos_residen_5adb34_idx')],
            },
        ),
    ]
