# Generated by Django 5.0.7 on 2025-12-17 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(help_text='Placa del vehículo (formato boliviano: 1852PHD)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='Formato de placa inválido. Use: 1234ABC o 1234-ABC (ej: 1852PHD)', regex='^\\d{4}[-\\s]?[A-Z]{3}$')]),
        ),
    ]
