# Generated by Django 5.0.7 on 2025-12-08 13:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0002_add_codigo_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato: YYYY-MM (ej: 2024-01)', max_length=7, verbose_name='Período')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Base')),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Multas, servicios extra, etc.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Adicional')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Pagado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_parcial', 'Pago Parcial'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensas', to='unidades.unidadhabitacional', verbose_name='Unidad Habitacional')),
            ],
            options={
                'verbose_name': 'Expensa',
                'verbose_name_plural': 'Expensas',
                'ordering': ['-fecha_emision', '-periodo'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto')),
                ('tipo', models.CharField(help_text='mantenimiento, agua, luz, multa, etc.', max_length=50, verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='pagos.expensa', verbose_name='Expensa')),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['tipo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], max_length=20, verbose_name='Método de Pago')),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de referencia, transacción, etc.', max_length=100, null=True, verbose_name='Número de Comprobante')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pagos.expensa', verbose_name='Expensa')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='expensa',
            index=models.Index(fields=['periodo'], name='pagos_expen_periodo_4276f4_idx'),
        ),
        migrations.AddIndex(
            model_name='expensa',
            index=models.Index(fields=['estado'], name='pagos_expen_estado_b66d36_idx'),
        ),
        migrations.AddIndex(
            model_name='expensa',
            index=models.Index(fields=['fecha_vencimiento'], name='pagos_expen_fecha_v_513500_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensa',
            unique_together={('unidad', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='pagos_pago_fecha_p_af939d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='pagos_pago_metodo__1a2e20_idx'),
        ),
    ]
